-- 자유 게시판
DROP SEQUENCE FREESEQ;
CREATE SEQUENCE FREESEQ;

DROP TABLE FREE;
CREATE TABLE FREE(
	-- 글 번호
	FREE_NO NUMBER PRIMARY KEY,
	
	-- 작성자
	FREE_WRITER VARCHAR2(100) NOT NULL,
	
	-- 글 제목
	FREE_TITLE VARCHAR2(1000) NOT NULL,
	
	-- 글 내용
	FREE_CONTENT VARCHAR2(4000) NOT NULL,
	
	-- 작성일자
	FREE_DATE DATE NOT NULL
);

SELECT * FROM FREE;

INSERT INTO FREE
VALUES(FREESEQ.NEXTVAL, 'JAYOUNG','자유게시판 테스트용','테스트용', SYSDATE);


-- 댓글
DROP SEQUENCE REPLYSEQ;
CREATE SEQUENCE REPLYSEQ;

DROP SEQUENCE REPLY_GROUPSEQ;
CREATE SEQUENCE REPLY_GROUPSEQ;

DROP SEQUENCE REPLY_GROUPNOSEQ;
CREATE SEQUENCE REPLY_GROUPNOSEQ;

DROP TABLE REPLY;
CREATE TABLE REPLY(
   -- 댓글 번호
   REPLY_NO NUMBER PRIMARY KEY,
   -- 아이디
   REPLY_ID VARCHAR2(100) NOT NULL,
   -- 댓글 남길 해당 글 번호
   REPLY_FREENO NUMBER NOT NULL,
   -- 댓글 그룹 번호 (대댓글의 기준이 될 원 댓글 순서)
   REPLY_GROUP NUMBER NOT NULL,
   -- 댓글 그룹 안에서의 순서
   REPLY_GROUPNO NUMBER NOT NULL,
   -- 대댓글을 달 때 들여쓰기 공백
   REPLY_TITLETAB VARCHAR2(10) NOT NULL,
   -- 댓글 내용
   REPLY_TITLE VARCHAR2(1000) NOT NULL,
   -- 댓글 작성일자
   REPLY_REGDATE DATE NOT NULL,
   
   -- REPLY_ID는 MEMBER_ID를 참조하는 Foreign Key
   -- (특정 MEMBER_ID가 삭제되면 해당 REPLY_ID도 삭제)
   --FOREIGN KEY(REPLY_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,

   -- REPLY_FREENO는 FREE_NO를 참조하는 Foreign Key
   -- (특정 FREE_NO가 삭제되면 해당 REPLY_FREENO도 삭제)
   FOREIGN KEY(REPLY_FREENO) REFERENCES FREE(FREE_NO) ON DELETE CASCADE
);


-- 댓글 리스트 조회
SELECT REPLY_NO, REPLY_ID, REPLY_FREENO, REPLY_GROUP, REPLY_GROUPNO, REPLY_TITLETAB, REPLY_TITLE, REPLY_REGDATE
FROM REPLY
WHERE REPLY_FREENO = #{replyfreeno}
ORDER BY REPLY_GROUPNO, REPLY_REGDATE;

-- 특정 댓글 조회
SELECT REPLY_NO, REPLY_ID, REPLY_FREENO, REPLY_GROUP, REPLY_GROUPNO, REPLY_TITLETAB, REPLY_TITLE, REPLY_REGDATE
FROM REPLY
WHERE REPLY_ID = #{replyid}
AND REPLY_TITLE = #{replytitle}
AND REPLY_FREENO = #{replyfreeno}
ORDER BY REPLY_NO;

-- 댓글 입력
INSERT INTO REPLY
VALUES (REPLYSEQ.NEXTVAL, #{replyid}, #{replyfreeno}, REPLY_GROUPNOSEQ.NEXTVAL, 1, 0, #{replytitle}, SYSDATE);

-- 대댓글 입력
INSERT INTO REPLY
VALUES (REPLYSEQ.NEXTVAL, #{replyid}, #{replyfreeno}, 
	-- 
	(SELECT REPLY_GROUP FROM REPLY WHERE REPLY_NO = #{parentreplyno}),
	-- 
	(SELECT REPLY_GROUPNO FROM REPLY WHERE REPLY_NO = #{parentreplyno}) + 1,
	-- 
	(SELECT REPLY_TITLETAB FROM REPLY WHERE REPLY_NO = #{parentreplyno}) + 1,
	#{replytitle}, SYSDATE);

-- 대댓글 순서 업데이트 (n번째 댓글의 n번째 대댓글)
UPDATE REPLY
SET REPLY_GROUPNO = REPLY_GROUPNO + 1
WHERE (REPLY_GROUP = (SELECT REPLY_GROUP FROM REPLY WHERE REPLY_NO = #{replyno})
AND REPLY_GROUPNO > (SELECT REPLY_GROUPNO FROM REPLY WHERE REPLY_NO = #{replyno}))
AND REPLY_FREENO = #{replyfreeno};

-- 글 번호 기준으로 댓글 갯수 카운트
SELECT COUNT(*) 
FROM REPLY
WHERE REPLY_FREENO = #{replyfreeno}

DELETE FROM REPLY;