DROP SEQUENCE FREE_SEQ;
CREATE SEQUENCE FREE_SEQ;

DROP TABLE FREE;
CREATE TABLE FREE(
	
	FREE_SEQ NUMBER PRIMARY KEY,
	
	FREE_WRITER VARCHAR2(100) NOT NULL,
	
	FREE_TITLE VARCHAR2(1000) NOT NULL,
	
	FREE_CONTENT VARCHAR2(4000) NOT NULL,
	
	FREE_DATE DATE NOT NULL
	
);
SELECT * FROM FREE
INSERT INTO FREE
VALUES(FREE_SEQ.NEXTVAL, 'JAYOUNG','자유게시판 테스트용','테스트용', SYSDATE);