--리플
DELETE FROM REPLY;
DROP SEQUENCE REPLY_SEQ;
DROP SEQUENCE REPLY_GROUPNO_SEQ;
DROP TABLE REPLY;

CREATE SEQUENCE REPLY_SEQ;
CREATE SEQUENCE REPLY_GROUPNO_SEQ;
CREATE TABLE REPLY(
   --댓글번호
   REPLY_NO NUMBER NOT NULL,
   --아이디
   REPLY_ID VARCHAR2(100) NOT NULL,
   --댓글남길 해당글의 번호
   REPLY_BOARDNO NUMBER NOT NULL,
   --댓글의 제목 및 내용
   REPLY_TITLE VARCHAR2(1000) NOT NULL, --댓글 내용
   --댓글 작성 날짜
   REPLY_REGDATE DATE NOT NULL,
   
   CONSTRAINT REPLY_NO_PK PRIMARY KEY(REPLY_NO),
   FOREIGN KEY (REPLY_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE,
   FOREIGN KEY (REPLY_BOARDNO) REFERENCES FREE(FREE_SEQ) ON DELETE CASCADE
  

);



INSERT INTO REPLY
VALUES(REPLY_SEQ.NEXTVAL, 'jayoung',62,'안녕',SYSDATE)

INSERT INTO REPLY
VALUES(REPLY_SEQ.NEXTVAL, 'jayoung',62,'댓글강제로 주입!',SYSDATE)

SELECT * FROM REPLY