DROP SEQUENCE CLASSSEQ;
DROP TABLE CLASS;

CREATE SEQUENCE CLASSSEQ;

CREATE TABLE CLASS(
	-- 강의 번호(PK)
	CLASS_NO NUMBER PRIMARY KEY,
	-- 강의 제목
	CLASS_TITLE VARCHAR2(1000) NOT NULL,
	-- 강사 ID
	CLASS_TEACHERID VARCHAR2(20) NOT NULL,
	-- 강사 이름
	CLASS_TEACHERNAME VARCHAR2(50) NOT NULL,
	-- 강의 타입
	CLASS_TYPE VARCHAR2(2) NOT NULL,
	-- 강의 대분류
	CLASS_BIGCATEGORY VARCHAR2(200) NOT NULL,
	-- 강의 소분류
	CLASS_SMALLCATEGORY VARCHAR2(200) NOT NULL,
	-- 강의 정보
	CLASS_INFO VARCHAR2(4000) NOT NULL,
	-- 강의 가격
	CLASS_PRICE NUMBER NOT NULL,
	
	-- 강의 타입 : CHK(W:Web-rtc(실시간 과외), V:Video(동영상 강의))
	CONSTRAINT CLASS_TYPE_CHK CHECK (CLASS_TYPE IN ('W','V'))
	-- 카테고리 : CHK(추가 해야 함)
);

CREATE TABLE IMAGEUPLOAD(
		
);
